language: go

services:
  - docker

script:
  - bash ./generate.sh

branches:
  only:
    - master

env:
  global:
    - secure="bvZWKuwBvpUqMoMMTkTtssQsAbq/pLX6EkMS2IHFylQvUCgltnEvYkMEKFbkII3B58yawxmAoKavaHX4uxSUwEyOnuc4nOXM4PatQLad3rIqoZ3aCudAf84dzZzHkX3nhUyPPYu0aWlFIu2ywz0TWUJaZ0dUHD+3kdrLDRdf5XKurKWbHEEiJ0hOk7lfNlb/iZD5bb3j1LjUi+GAczay6UcrYw/PJbThPqz0OUskr5Gsjk8nPqZ4rFXmMW9GFQS1RDjd5TUbS8Bgh2+JKyCddKApVBrtRAyX0XrOpr7yXPHSIIcshxhtuKTiYwnIhs9SwhSQLwiUJzoPLXWFJmXQ9EY0G1FkGA65vdbcR7mV2K/+fvAll/+CiGt+HXO3jZcqboBDGqnUi0mJzDdJzA5TVNuXBQTSHvX+IPsFrv+BsDsqv5VXLV+2Yx2E2SGb1XssI4dbMgZsT/fkxu31/utv/wyK9GLMjjLOWLOJjWzfnU6HxRYwwOGeZZUAO/m49zust16SHiAlIBtBJ3YIE+8DEyYyvrLgPaWgFrXMTSRbsGUsu6MkWjIDVWb5BK6eD8vzDw5MvYbhI1JNl9IbLZxaMj5giaw7l4BWHURnL50SF2WldjQf2bGvonDjb0btY98HMh5DtMy7dcVcgu5kOl//56uJMmleDmD5r2zVB9PEeMw="
